version: '3'
services:
  web:
    build: .
    restart: unless-stopped
    links:
      - db
    depends_on:
      - migration
    env_file:
      - ./.env
  migration:
    build: .
    links:
      - db
    command: [ npm, run, migrate ]
    env_file:
      - ./.env
  db:
    image: postgres:12.11-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - ./db.env
    ports:
      - 5432:5432
  redis:
    image: redis
    ports:
      - 6379:6379
